version: '3.8'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=bulletin
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build: .
    command: gunicorn3 --config /deploy/app/gunicorn_config.py bulletin.wsgi:application
    depends_on:
      - db
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_HOST=db
      - ENVIRONMENT=docker
    ports:
      - 8080:8080
    volumes:
      - ./bulletin:/deploy/app/bulletin
