service: bulletin
plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: bulletin.wsgi.application
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
    zip: true
    noDeploy:
      - pytest
      - pytest-django
package:
  exclude:
    - node_modules/**
    - script/**
    - venv/**
provider:
  name: aws
  runtime: python3.7
  timeout: 30
  stage: develop
  region: us-west-2
  environment:
    ENVIRONMENT: production
    SECRET_KEY: ${ssm:BULLETIN_SECRET_KEY}
    DATABASE_HOST: ${ssm:BULLETIN_DB_HOST}
    DATABASE_USER: ${ssm:BULLETIN_DB_USERNAME}
    DATABASE_PASS: ${ssm:BULLETIN_DB_PASSWORD}
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
