#!/usr/bin/env bash

#
# SERVER
# is used to start the application.

usage()
{
    echo "usage: server [[-g gunicorn ] | [-h]]"
}

# optional argument(s)
while [[ "$1" != "" ]]; do
    case $1 in
        -g | --gunicorn )       shift
                                gunicorn=1
                                ;;
        -h | --help )           usage
                                exit
                                ;;
        * )                     usage
                                exit 1
    esac
    shift
done

ROOT="$( dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )")"

# Ensure scripts are running from the correct environment
"${ROOT}"/script/bootstrap

# Run project
if [[ "$gunicorn" == "1" ]]; then

    # Install gunicorn if not available
    if [[ "$(command -v gunicorn)" != "$ROOT/venv/bin/gunicorn" ]]; then
        echo "Installing gunicorn..."
        pip install 'gunicorn>=19.9.0'
    fi

    gunicorn --config "$ROOT/gunicorn_config.py" bulletin.wsgi:application

else
    python3 "${ROOT}"/manage.py runserver 0.0.0.0:8080
fi
